# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: DI - rolling build

pr:
  branches:
    include:
      - master
      - features/*
      - fixes/*
      - releases/*

trigger:
  - master
  - features/*
  - fixes/*
  - releases/*

pool:
  vmImage: windows-latest

steps:

- task: UseDotNet@2
  displayName: Install .NET 5.0
  timeoutInMinutes: 5
  inputs:
    packageType: 'sdk'
    version: '5.0.x'

- task: NuGetCommand@2
  displayName: Restore solution
  timeoutInMinutes: 10
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    configuration: Debug

- task: VSBuild@1
  displayName: Build solution
  timeoutInMinutes: 30
  inputs:
    solution: '**\*.sln'
    configuration: 'Debug'
    maximumCpuCount: true
    msbuildArchitecture: 'x64'